# Generated by Django 2.0.7 on 2018-07-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='excerpt',
            new_name='body',
        ),
    ]
